spring.application.name=StudentManagementWebApp

spring.datasource.url=jdbc:mysql:///MyProject
spring.datasource.username=jatin
spring.datasource.password=Jatin@6116

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/StudentApp